# roles/ROLENAME/tasks/main.yml
---

- name: Install packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items: ROLENAME_packages
  tags: ROLENAME

- name: Ensure service is started
  service:
    name: "{{ ROLENAME_service }}"
    state: started
    enabled: true
  tags: ROLENAME
